/*
 * generated by Xtext
 */
package ru.bmstu.rk9.rdo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RDOUiModule extends ru.bmstu.rk9.rdo.ui.AbstractRDOUiModule {
	public RDOUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
