/*
 * generated by Xtext
 */
package ru.bmstu.rk9.rdo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.builder.IXtextBuilderParticipant;

import ru.bmstu.rk9.rdo.ui.MultipleResourceBuilderParticipant;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RDOUiModule extends ru.bmstu.rk9.rdo.ui.AbstractRDOUiModule {
	public RDOUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		return MultipleResourceBuilderParticipant.class;
	}

}