/*
* generated by Xtext
*/
package ru.bmstu.rk9.rao.ui.labeling

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */

class RaoDescriptionLabelProvider extends org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider {
}
