/*
 * generated by Xtext
 */
package ru.bmstu.rk9.rao.ui.labeling

import com.google.inject.Inject

/**
 * Provides labels for EObjects.
 *
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
class RaoLabelProvider extends org.eclipse.xtext.xbase.ui.labeling.XbaseLabelProvider {
	@Inject
	new(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
}
