/*
 * generated by Xtext
 */
package ru.bmstu.rk9.rao;

import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

import ru.bmstu.rk9.rao.generator.RaoGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */

public class RaoRuntimeModule extends ru.bmstu.rk9.rao.AbstractRaoRuntimeModule {

	public Class<? extends ILinkingDiagnosticMessageProvider> bindILinkingDiagnosticMessageProvider() {
		return RaoLinkingDiagnosticMessageProvider.class;
	}

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return RaoQualifiedNameProvider.class;
	}

	public Class<? extends IMultipleResourceGenerator> bindIGenerator2() {
		return RaoGenerator.class;
	}
}
