/*
 * generated by Xtext
 */
package ru.bmstu.rk9.rao;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RaoRuntimeModule extends ru.bmstu.rk9.rao.AbstractRaoRuntimeModule {

}
