/*
* generated by Xtext
*/
package ru.bmstu.rk9.rao;

/**
 * Initialization support for running Xtext languages without equinox extension
 * registry
 */
public class RaoStandaloneSetup extends RaoStandaloneSetupGenerated {

	public static void doSetup() {
		new RaoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
