/*
 * generated by Xtext
 */
package ru.bmstu.rk9.rdo.ui.contentassist

import ru.bmstu.rk9.rdo.ui.contentassist.AbstractRDOProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RDOProposalProvider extends AbstractRDOProposalProvider {
}
